begin;

alter sequence article_comment_id_seq restart with 1;
alter sequence article_id_seq restart with 1;
alter sequence article_like_id_seq restart with 1;
alter sequence client_id_seq restart with 1;
alter sequence image_id_seq restart with 1;
alter sequence product_comment_id_seq restart with 1;
alter sequence product_id_seq restart with 1;
alter sequence product_like_id_seq restart with 1;
alter sequence product_tag_id_seq restart with 1;
alter sequence tag_id_seq restart with 1;



insert into client
	(email, provider, provider_id, nickname, password)
values
('thester@example.com', 'discord', 1, 'christopher49', NULL),
('brittanyriley@example.net', 'naver', 2, 'acox', NULL),
('vwhitaker@example.org', 'discord', 3, 'garycooper', NULL),
('smann@example.com', 'kakao', 4, 'elizabeth23', NULL),
('dominique11@example.org', 'google', 5, 'david42', NULL),
('mcleanzachary@example.net', 'local', 6, 'edwardkent', '4119'),
('gsandoval@example.net', 'discord', 7, 'evansdavid', NULL),
('michellemorse@example.com', 'naver', 8, 'palmerapril', NULL),
('kmorris@example.org', 'local', 9, 'frederickchristine', '5870'),
('fdavis@example.com', 'discord', 10, 'watkinschristopher', NULL),
('leonardanthony@example.net', 'naver', 11, 'stevenking', NULL),
('hhodges@example.com', 'local', 12, 'aliciapoole', '3060'),
('markrobbins@example.org', 'discord', 13, 'richardsonchristian', NULL),
('morrisstephen@example.net', 'naver', 14, 'vargasjames', NULL),
('kbenson@example.com', 'local', 15, 'brandondavis', '1226'),
('alyssarodriguez@example.com', 'google', 16, 'mark73', NULL),
('tannerryan@example.net', 'discord', 17, 'wilsonkristin', NULL),
('jennifermaldonado@example.net', 'naver', 18, 'lynn07', NULL),
('gutierrezlinda@example.org', 'discord', 19, 'madeline92', NULL),
('deanna53@example.net', 'discord', 20, 'joe17', NULL),
('rothsean@example.com', 'kakao', 21, 'michaelestrada', NULL),
('ahudson@example.com', 'discord', 22, 'faithporter', NULL),
('davidmcmillan@example.com', 'discord', 23, 'teresa05', NULL),
('dayjames@example.net', 'discord', 24, 'vhaley', NULL),
('briana35@example.com', 'local', 25, 'shawashley', '4440'),
('davidadams@example.net', 'local', 26, 'francofrank', '279'),
('rlee@example.net', 'discord', 27, 'cameroncross', NULL),
('lindsaygonzalez@example.com', 'naver', 28, 'hbauer', NULL),
('calderondeborah@example.org', 'google', 29, 'bianca30', NULL),
('hannalori@example.net', 'kakao', 30, 'joshua95', NULL),
('cohenmaria@example.net', 'local', 31, 'anaortega', '8933'),
('istewart@example.com', 'google', 32, 'vturner', NULL),
('kendrabaldwin@example.org', 'google', 33, 'taylor65', NULL),
('tbrowning@example.org', 'google', 34, 'johngomez', NULL),
('grahamcheryl@example.com', 'kakao', 35, 'michaelwagner', NULL),
('littlechristopher@example.com', 'discord', 36, 'james53', NULL),
('haroldpark@example.com', 'naver', 37, 'ronald66', NULL),
('lramirez@example.net', 'naver', 38, 'gmartinez', NULL),
('raymond53@example.com', 'google', 39, 'jgibbs', NULL),
('richardsonsamuel@example.org', 'discord', 40, 'fwoods', NULL);

insert into article
	(title, content, client_id)
values
('List grow', 'Along strong resource laugh statement also discuss. Answer spring prove important.', 1),
('Relate pu', 'Likely now evidence nice. Eat small than may expect.', 2),
('Financial', 'Box important oil population eight. Free education dream every girl.', 3),
('Finally t', 'Star everything center relate stand. Can just focus. Bed according report consider fear.', 4),
('Case ever', 'Return likely give. Whom game big general.', 5),
('Important', 'Head point particularly raise bar meet. Position might tough discussion six prove trip. This no drug.', 1),
('Nor day i', 'Mr read risk least station white pretty movie. By mother produce put continue raise I.', 2),
('Knowledge', 'Standard book financial. If remain figure finally property interview century.', 3),
('Process o', 'Say light adult year. Yard federal seat black.', 4),
('Computer ', 'Left social picture town billion moment talk. Tv just always important put others young.', 5),
('Price som', 'When marriage information seek story remain nice artist. Yourself that prepare cell another teacher either.', 1),
('Structure', 'About worry between alone provide. Particular minute tough thank official left put.', 2),
('Player po', 'Detail any rise purpose than. Them news pass international house operation. Visit section front mission campaign.', 3),
('Box appea', 'Opportunity her like discuss must information close. Try rock glass actually easy.', 4),
('Democrat ', 'Painting together action himself rule watch significant. Direction hour test store reduce. Meeting change see always phone.', 5),
('Beat anyt', 'Kitchen operation need fall career. Off those what president compare actually firm source. Bar majority speak quickly base left possible.', 1),
('Pressure ', 'Kind guess item only movement season. Cost check development wide base your. Force million human question to professor.', 2),
('Director ', 'Media tough plant animal. Rich player box phone.', 3),
('Strategy ', 'Main very reduce hotel yes task. Assume include believe education order little group. Doctor other show. On black write nature forget form court.', 4),
('Enjoy los', 'Smile adult land whatever make education task order. Ball foreign himself. Air thousand up evening body.', 5),
('Store mee', 'Lawyer both carry traditional. Picture must throw table. Box girl clearly lawyer ball stay require.', 1),
('May meet ', 'Democrat wrong above sister expert onto. Well direction responsibility.', 2),
('Hour plan', 'Hospital from window chance Democrat young. Medical main employee lose democratic middle later. One information religious truth.', 3),
('Any tell ', 'Religious hand down project various conference give. Dream pull beyond reduce her world close rest. Must author base chair fact group early church.', 4),
('Near pape', 'Local eat student then. Future outside amount huge national. General professor ago sea own certain wrong program.', 5),
('Goal note', 'Speech main meeting who everybody world popular. Team certain however wrong gas task process. We maybe water job tell writer. Nearly south stage billion.', 1),
('Professio', 'Over to eye what wish cell question.', 2),
('North for', 'Practice challenge much somebody friend assume also. Read no new receive save.', 3),
('Yes capit', 'Scientist able test. Possible sea show. Live fund imagine state check happy.', 4),
('Near cult', 'Require cell this control pressure. Among mention attention such popular.', 5),
('Outside t', 'Idea employee music moment environment why. Life several future himself after sometimes attention.', 1),
('Energy de', 'A individual agency resource enter society painting. Yeah out base enter wall. Child series interest.', 2),
('Toward ne', 'Her provide meet ground billion car. Law class financial.', 3),
('Hot charg', 'Sure candidate remain detail friend. While sign firm lawyer sell face do.', 4),
('Ready nea', 'They enjoy animal build protect win. Bank knowledge huge rest more word very.', 5),
('Indicate ', 'Population story gun soldier. Leader water she owner. Society bed number speech.', 1),
('Produce l', 'Rest name ball current option station list pick. Account sure third history.', 2),
('Create po', 'Also age especially simple always civil. International law break behavior often meet improve.', 3),
('Usually q', 'Produce recognize happy coach people here see. Visit entire like professor. Free most successful threat beat behind education heavy.', 4),
('Fish wish', 'Be easy adult your result. Stock man likely. Put shake role outside. International should agreement so conference his plan.', 5),
('Occur wor', 'Travel matter cold that Congress event public security. Little career money only must dog many race.', 1),
('Explain w', 'Ok age identify direction good. Senior region car if.', 2),
('Pattern b', 'Check wait skill order. Admit general local as firm.', 3),
('Up line r', 'Happen from often. Best million fund accept. Politics southern western special adult message. Worry available network apply.', 4),
('Cause ava', 'Expert against single effect. Brother phone measure.', 5),
('Board lea', 'Myself any trouble save.', 1),
('Memory se', 'Mr discussion stay manager lead west various. Themselves recent discover fish moment that.', 2),
('Region be', 'Church century relate break play. Ago already also stage yet party participant.', 3),
('Likely as', 'Organization leg parent involve support successful hit. Ability environmental through really many determine approach weight.', 4),
('Environme', 'Include manage law respond create cost skin about. Sign smile compare in firm attorney strong. Hard very citizen product specific practice.', 5),
('Need expe', 'Another point enjoy agreement interview baby especially.', 1),
('Forget cu', 'Industry rock market resource join amount size. His sing century item save push participant rate. Husband which law particular would play task team.', 2),
('Receive a', 'Land foot present form. Record policy air red least state American. Together skin owner that ever less social.', 3),
('Down inst', 'Capital shake together language. Evidence can sometimes recent however west. Other meet strong no decide environmental once billion.', 4),
('Knowledge', 'Interesting agree yes. Nothing member glass authority institution over visit. Building prepare cell listen choice.', 5),
('Particula', 'Fund kid level form. Relate worry could.', 1),
('Cover mus', 'Although one high school cost particularly. Federal billion and through wish sell cup result.', 2),
('Third edg', 'Leader piece treatment either anyone himself risk. Character me kitchen point success operation offer land. Send down return wall north business. Experience job event determine first as officer plan.', 3),
('Record ch', 'Structure wonder idea. Effect me large miss let anyone.', 4),
('Fish cell', 'Left Republican threat later yard what walk. Sport agreement yard may heavy million.', 5),
('Writer se', 'Maybe kind school operation include include music such. Short fill outside example different together happen. Do election community.', 1),
('Develop w', 'Station you something kid story.', 2),
('Main civi', 'Development certain never early water account meet billion. All catch provide recently suggest. Difference process card true brother air professional help.', 3),
('Social pu', 'Measure season industry who. For our near. Interesting explain sister especially see.', 4),
('Resource ', 'Choose dark close color inside scientist. There buy themselves night. Media rate hotel green.', 5),
('Populatio', 'Large more beat five. Live physical else development spend evidence serve. Expect middle institution head no decision.', 1),
('Billion p', 'Week ago either which. Protect require financial rock.', 2),
('Professor', 'Sometimes social throw impact reduce day. Low six issue probably around poor nor sea. Table day heart here final take.', 3),
('Born line', 'Control enough model we. Including chair fill should story large matter. Perform push prepare high.', 4),
('Art heart', 'Recent last range system cost subject various. So which again break fight program figure. World admit decision product knowledge.', 5),
('Former se', 'Reflect field message recent phone property rise indicate. Claim first receive wrong half. Election class here despite notice nor plant.', 1),
('Subject f', 'Wide time along.', 2),
('Training ', 'Establish whose mind keep decide movie. Offer southern them pull total.', 3),
('Window fa', 'Evening Congress itself world. Put spring while probably car. Assume certainly oil buy them price type.', 4),
('Effect by', 'Season attack term relate population seat. City admit effort send someone property care.', 5),
('Argue wes', 'Student produce lose much Congress include PM. Travel when thousand trouble door yourself kitchen. Decade might establish environment boy open.', 1),
('Mind nece', 'Large must Mrs participant can will hospital. Speak gas now sea party doctor national single.', 2),
('Eat sprin', 'City born Mr maintain every. Another task people trouble meet perform.', 3),
('Arm bit v', 'Glass then make large four compare walk. Again sit environmental worker success analysis concern.', 4),
('Lead oper', 'Start reflect successful receive four visit positive. Speech above serious eight short modern open smile. Available exist buy argue trouble win. Despite least three as character available.', 5),
('Human mod', 'Human central interest per keep. Thing region style history his month. Community southern no nature admit.', 1),
('In fund f', 'Environmental discussion response. Environmental against sure current company again behavior.', 2),
('Exist spo', 'Tonight themselves enough he. Someone big toward bank question nation.', 3),
('Opportuni', 'Whatever course ever building. Training black option music employee energy. Company also pass strategy focus method.', 4),
('Experienc', 'Late become while thousand suggest before like. Song build suggest radio west.', 5),
('Money sto', 'Group professional executive attorney at. Guess difference system power their. Professional reality fire condition cost quickly better.', 1),
('Hospital ', 'Marriage scene next team factor listen office hand. Culture culture section increase describe success truth. Threat agreement particularly.', 2),
('Thank fol', 'Himself according yeah cover station. Congress service understand dark air.', 3),
('Point mor', 'Without head term. Culture start change development because. New place TV.', 4),
('Blue econ', 'Western society trade election reduce visit strategy. Own mouth statement sense later rock. Well million be million. Each add with cover beyond future later.', 5),
('Organizat', 'Bed word open five. Perhaps describe article model offer glass fire. Fill son avoid.', 1),
('Unit fore', 'She respond clear. Money center step main. Name high drug change might move skin.', 2),
('Against c', 'Minute including own.', 3),
('None seas', 'Help leg today third relationship. Could could from often point eat country.', 4),
('Exist sid', 'System result possible central factor professional article. Audience over Congress.', 5),
('Author th', 'Know doctor spend maybe really sea machine political. Choose wife because share suffer support. Shoulder call red job.', 1),
('Dog prepa', 'Page performance find.', 2),
('Million c', 'Nothing enter try want nature experience late. Purpose law maintain officer actually compare keep. Free fine kind late compare.', 3),
('Cultural ', 'Total fire imagine democratic personal. Kitchen particularly those red water each list.', 4),
('Character', 'Fight west successful contain point. International education field the.', 5),
('Nothing s', 'One industry father agree president.', 1),
('Fill envi', 'Third position perform sister agency create but. Why send sell between cause. Child receive court simple.', 2),
('Away week', 'Question thought evening southern move else. Dinner oil glass reach assume garden respond fact.', 3),
('Threat gu', 'Might body near sound simply able. Serve day wide idea seem last mention. Personal production data environment network.', 4),
('Effort fi', 'Tell represent service. Make economic Congress. Fly sea require section.', 5),
('And stuff', 'Suffer year instead these behind reason voice. Road why behind add expert expect great. Write then make station positive.', 1),
('Offer nat', 'Just class president yet camera majority. American red floor nation.', 2),
('Course sh', 'Mrs party certainly major artist talk white. And level institution identify pay her.', 3),
('Wind stil', 'Ready actually south rather experience however hotel. Already yard phone school.', 4),
('Road part', 'Month throw thing fast. Back material dark.', 5),
('Get pick ', 'Mouth future activity public five production. Kitchen much avoid lot that central. Somebody west anything very house.', 1),
('Finally m', 'Major across right religious piece explain always simple. Most hit pass represent likely beat stage.', 2),
('Analysis ', 'Travel read consumer across once morning kind. Would perhaps decade his he account. Bit continue movie medical main know major instead.', 3),
('Relations', 'Seven sound record. Cup foreign but plant. Memory I fill serious however production court.', 4),
('Attorney ', 'Conference necessary kid one. Direction speak foreign game out call safe.', 5),
('Result pr', 'Discover person hope standard her site. Begin decision serious.', 1),
('Follow pr', 'Participant ability maintain sport understand concern. Break together anything now out. Story certainly central them.', 2),
('Hold tax ', 'Street more month should human. Open magazine floor case water past computer very.', 3),
('Concern s', 'Apply quality bill.', 4),
('Turn firs', 'Two worker science sing write none practice. After we whose power recognize why present. Develop four gun bar community management town.', 5),
('Admit nic', 'Difference box cost field thought father business community. Hit official discussion magazine.', 1),
('Tell wish', 'Provide whatever work. Nearly me explain few mention. Book free result head.', 2),
('Film land', 'But pull where peace local compare worker work. Soon better because notice federal. Power business officer. Worker hand anyone positive.', 3),
('Style wea', 'Operation think treat.', 4),
('Along abo', 'Though person large your. Air hotel wear above. Election begin pattern ball in available.', 5),
('Happen fa', 'Mean expert glass control case attention. Man learn writer pressure individual none.', 1),
('Exist sub', 'Suggest power name pull capital kid newspaper nation. Our national eight cause watch send. Rise same role attention leg tell animal.', 2),
('Work some', 'Happy recently our money run meeting reason. Eight walk explain wish let build. Both sing strategy mission bad.', 3),
('System im', 'Open scene reality feeling thus decade land season. Wrong head high surface oil. Blood inside white support chance. Herself kitchen authority support sing green some.', 4),
('Election ', 'Seat share present. Pretty her summer sound soon offer. And she computer development will continue.', 5),
('Morning n', 'Executive call be tell industry series. Take officer example according gun plant feel.', 1),
('Kind degr', 'Drug good current science throw scene wife quickly. Say attorney around type.', 2),
('Organizat', 'Animal ground save talk choose radio. Relationship sport relationship minute. Customer choose nature.', 3),
('Increase ', 'Value look to door coach method. End by magazine discuss.', 4),
('Office in', 'Plan owner certainly. Everyone account course type.', 5),
('Without k', 'Discussion worker center seat majority less sister. Quite yourself product keep.', 1),
('Account w', 'Fight agreement already add put scientist health. Voice deal successful walk yourself. Effort trip possible tough though.', 2),
('Hair anal', 'Send feeling spring. Research practice page room ability nice adult. Each authority doctor level affect available low eye.', 3),
('Image min', 'Town necessary question woman ask man. Memory ability culture decade although. Almost own call sense major question third.', 4),
('Tree proc', 'Hard reach person vote bad recognize research. Reduce human she. Leave think bill finally point. Author author within either town remain lot generation.', 5),
('Pretty au', 'Change guess shoulder. We increase else sell paper into. Dog election word. Try site let mother well.', 1),
('Task chai', 'Matter citizen happen the financial. Reach happy note administration chance recognize them his. Glass similar approach fact factor. Decade feel late different himself direction suffer.', 2),
('Risk six ', 'Wonder body fall would almost understand. Chance environmental perhaps local increase right treat call. Foot character provide body however commercial far. Stuff strategy store.', 3),
('Happen du', 'Seek organization artist or several. Nor few plan begin term sure.', 4),
('Find keep', 'Option send national who itself. Need issue able significant road animal.', 5),
('Assume me', 'Move save per morning improve tough until loss. Meet approach wife clearly modern instead staff. From spring religious see. Most hear add performance president feel.', 1),
('National ', 'Nation realize involve its information expect late picture. Surface walk rather happen eye human.', 2),
('Other all', 'Another morning time little me such war. Feel yes be detail popular bad worry.', 3),
('Back some', 'Me certainly sister serious society professor series. Family cut American character. Paper authority seat past.', 4),
('Sit rule ', 'Live contain design life through. Different crime young let. Tell clear west spend she. Training ability people daughter ready political be.', 5),
('Major sim', 'Back right value vote government. Three them trial.', 1),
('Smile the', 'Side professor change lose guess least. Card walk enjoy represent. Bag nation trip.', 2),
('Light mus', 'Specific rich together. Myself mention determine see fear.', 3),
('Great bit', 'Car modern political. Board lawyer new minute first start. Relate store way national scene.', 4),
('Condition', 'Clearly song call perform with late professor. Bit dinner manager suffer. Other pretty hand simple feeling rule office.', 5),
('Yourself ', 'Herself machine contain involve attack style. News design but across visit science doctor. During kind major street prove event million special.', 1),
('Toward st', 'Different close act school could affect. President best picture morning less like.', 2),
('President', 'Occur fear movie middle have may. May news at imagine.', 3),
('Give auth', 'System choose world dream. Use available onto view specific. Left lead door heart summer yard different.', 4),
('Throw cut', 'Themselves lay let me sense home any. Building something value perhaps car recent door.', 5),
('Expect he', 'Letter thousand resource heavy floor week grow meet. Key but and well edge sit.', 1),
('Off keep ', 'Performance standard news yard point. Trial care news score area.', 2),
('Capital a', 'Some build wrong whatever year win million. Class baby practice receive simple.', 3),
('Can invol', 'Weight tax nation image certainly senior use.', 4),
('Home reme', 'Enjoy section cause remain former seat. Good call walk mean day allow. Cell might degree throughout continue suggest.', 5),
('With miss', 'Respond indicate reflect film actually.', 1),
('Way clear', 'Capital production month visit drop heart begin wife. War policy man home. Product late goal whose program whether city trouble.', 2),
('Both shou', 'Serve share tough executive myself no prepare condition. Heavy discuss staff character arm strong building.', 3),
('Parent by', 'Opportunity score source style. Have resource economy.', 4),
('Prepare d', 'Article recently remember light growth worker from. Sell campaign cause majority old thought project.', 5),
('Move trad', 'Boy garden while north act. Produce note forward candidate lead reflect image million.', 1),
('Senior na', 'Former senior real old and cut. Wonder forget just there peace. Part final future east together bill.', 2),
('Perform w', 'Memory heart campaign law. College itself entire out create event certain.', 3),
('Use posit', 'Land check ready light. Responsibility once than memory night want.', 4),
('Realize a', 'Left trouble rate trip pressure. As be task her. Until indicate worker tree.', 5),
('Cut admin', 'Administration indicate as particularly. Market bar I religious upon.', 1),
('Administr', 'However color prevent defense I form peace. Including certainly skin family throughout truth anything.', 2),
('Real cult', 'Program leader write deal girl size none. Century road car child hit training task prevent.', 3),
('Out rate ', 'Smile whom above serious end. Instead tree full letter yard.', 4),
('Build ins', 'Rule exactly increase against. Appear carry reveal produce. Computer former call everything author some return.', 5),
('Election ', 'Relationship part model. Learn tax that interest others over. List high career east sure plant.', 1),
('Care art ', 'Yeah toward guess up central name much. Measure site hear candidate drug.', 2),
('Firm pret', 'Most professional check. Important PM training future husband which easy.', 3),
('Policy re', 'Even around father protect case conference herself.', 4),
('Scene fil', 'Shake few law. Help space above recognize. Everything compare resource impact.', 5),
('Operation', 'Several writer sure word light improve investment. Per should for vote those indeed.', 1),
('Perform y', 'Kitchen shoulder despite rise every computer require. Sit put significant gas yard behavior.', 2),
('Food acco', 'Statement meet continue rule draw game process. Receive financial buy bag partner.', 3),
('This end ', 'Third power somebody beat notice. Treat clear piece wait item reduce name.', 4),
('Hot produ', 'Produce put his product. Three name ten feel arm. Type east standard cut have.', 5),
('High doct', 'Art continue social parent. Nation much stage also.', 1),
('With sign', 'Government reduce star. While food charge life for simple.', 2),
('Practice ', 'Toward just customer assume. None space lose. Reality set nor technology third rather.', 3),
('Chance tr', 'Protect despite tree evidence address. Car many her player outside face.', 4),
('Increase ', 'Various determine traditional sometimes personal loss boy. Throughout be ability listen evidence behind than. Assume system red safe these inside girl.', 5),
('Onto act ', 'Us brother not term office must certainly necessary. Region store the leave.', 1),
('Improve t', 'Sense couple notice camera. Assume would side special such. Ten show major state form one.', 2),
('Son under', 'Ever music culture perform. Month technology man knowledge enjoy age than top.', 3),
('Fall rece', 'He study represent figure watch. Participant hand summer executive position risk. Difficult contain pattern fact himself.', 4),
('Rise vari', 'Teach draw PM very garden almost. Way order glass get. Theory Mr move turn.', 5);

insert into article_comment
	(content, article_id, client_id)
values
('Interview inside professional use notice attention.', 5, 1),
('Military indicate although behavior put.', 1, 2),
('Woman coach happy news stage various officer.', 1, 3),
('Scene peace growth likely.', 1, 4),
('Impact continue at tough.', 4, 5),
('People lay man name admit raise while.', 3, 6),
('Include teacher respond organization on.', 3, 7),
('Act short myself grow hospital.', 1, 8),
('Election it those point position.', 1, 9),
('Simple between provide Mr authority.', 5, 10),
('Explain once involve upon age yourself paper.', 5, 11),
('Baby sort factor I type with memory.', 2, 12),
('Man watch letter around center.', 5, 13),
('Nearly toward benefit after imagine decision success collection.', 4, 14),
('Benefit glass other trade adult happen.', 4, 15),
('A break future pressure very sure rest catch.', 3, 16),
('Coach hold miss somebody real southern.', 5, 17),
('Physical area once line page.', 2, 18),
('Professional consumer billion general.', 4, 19),
('Child property type Congress network customer town.', 2, 20),
('Between leader design item already human.', 3, 21),
('When realize fire collection take on.', 2, 22),
('Raise break key.', 4, 23),
('Test him become painting time budget.', 4, 24),
('Well put about bar.', 4, 25),
('Culture available experience professional measure money activity fear.', 4, 26),
('Financial help general on produce body.', 1, 27),
('East whatever seat.', 2, 28),
('Already study behavior page modern chance.', 1, 29),
('Safe meet size spend often able.', 3, 30),
('Rock law look action once administration inside.', 3, 31),
('Have summer simple dark worker.', 5, 32),
('Music approach use safe seat.', 1, 33),
('School call ok because pass listen administration.', 5, 34),
('Traditional must feel picture art follow.', 3, 35),
('Style image do wear statement.', 3, 36),
('Area give early exist contain start or.', 3, 37),
('Girl expect information set employee.', 1, 38),
('Finally professor near.', 1, 39),
('Play dark prove professional.', 5, 40),
('Evidence develop industry fish culture.', 5, 1),
('Charge majority staff safe everything anyone century.', 4, 2),
('Check off her body over garden.', 5, 3),
('Both national treat.', 2, 4),
('Newspaper college force expect speech each.', 5, 5),
('Guess during education official prevent range.', 2, 6),
('We relationship world compare.', 1, 7),
('Young career consider finish care.', 5, 8),
('Identify return bar no.', 3, 9),
('Democrat daughter perform black cultural.', 2, 10),
('Make design improve benefit growth growth.', 1, 11),
('Necessary artist professor prove drive almost.', 3, 12),
('Artist challenge end gun friend up six.', 1, 13),
('Music rather TV skin guess.', 3, 14),
('Call military point.', 2, 15),
('Suggest me Mr allow political.', 3, 16),
('Organization among marriage perhaps.', 4, 17),
('Include art myself sell.', 3, 18),
('President major say believe picture instead list.', 4, 19),
('Material see important skill white.', 5, 20),
('Serve where campaign concern teacher chance least.', 3, 21),
('While really cell chance movement personal social.', 1, 22),
('Method good sign full while head.', 3, 23),
('Base wish chance keep interesting within wonder.', 3, 24),
('Go process group force available system than.', 2, 25),
('Course their sign mouth.', 2, 26),
('Then throughout never fear group term PM.', 2, 27),
('Protect force require dinner.', 5, 28),
('Reduce benefit truth peace.', 3, 29),
('Born before change meeting support natural image.', 1, 30),
('Garden road read international share.', 5, 31),
('Drive method laugh situation indicate woman.', 5, 32),
('Maintain political six dream fear economic mother.', 1, 33),
('Experience stay nature.', 5, 34),
('Interest off coach leader speech.', 5, 35),
('Help which hospital.', 4, 36),
('Detail rate detail over response rule.', 2, 37),
('Drive head key my.', 3, 38),
('Too technology person discover.', 2, 39),
('Eight own former interesting include Mrs.', 4, 40),
('Nearly television response.', 1, 1),
('Choose friend main evidence both.', 4, 2),
('World left address mean.', 5, 3),
('Before relationship single line phone training.', 3, 4),
('Head social role understand pressure point system.', 5, 5),
('Citizen rock science employee talk.', 3, 6),
('Lawyer writer no ago seven wait whatever player.', 5, 7),
('Card my than ask appear nearly.', 4, 8),
('Technology road government listen care movement.', 4, 9),
('Coach cover figure maybe.', 3, 10),
('Reality able believe or hospital.', 5, 11),
('Plant collection particularly decide take.', 1, 12),
('Type star resource life state ok.', 4, 13),
('Set born reality trade late husband hour.', 2, 14),
('Minute seat street heart anything.', 5, 15),
('Now bill successful allow left.', 5, 16),
('Real game every western more technology give.', 1, 17),
('Maintain manage dream type institution place.', 1, 18),
('Election on available again note majority.', 3, 19),
('Majority arrive rich dark.', 2, 20),
('Challenge machine happen check crime painting.', 4, 21),
('Mrs agency rate analysis.', 3, 22),
('Southern open suggest yes subject.', 4, 23),
('Although go out decide heart plant.', 1, 24),
('Million say activity cold arm appear or apply.', 1, 25),
('As when option rather each.', 1, 26),
('Stuff feeling benefit make their believe still.', 1, 27),
('Federal thought young reach pick own quickly join.', 1, 28),
('Country offer everyone yet various want.', 3, 29),
('Plan apply fill back without alone.', 3, 30),
('Network soldier natural lead including everybody.', 5, 31),
('Even four simply.', 4, 32),
('Cut someone animal night who.', 4, 33),
('Executive dinner thank and meet middle miss theory.', 5, 34),
('I social trouble rule.', 1, 35),
('Structure term onto money huge foreign rate.', 5, 36),
('Happy doctor door inside.', 2, 37),
('Pay hear when local turn.', 4, 38),
('Treat country speech.', 1, 39),
('Tell happy only military during head realize.', 2, 40),
('Source successful watch another compare.', 4, 1),
('Call performance also successful.', 2, 2),
('Environmental be treat read seek.', 5, 3),
('Seek some travel how lay something fight.', 5, 4),
('Policy relate far officer later future.', 4, 5),
('Science house night strong candidate.', 2, 6),
('Hotel describe forward realize now during agency site.', 4, 7),
('Through new service.', 4, 8),
('Talk itself community form science.', 4, 9),
('But enough professional point fund word level.', 2, 10),
('Employee leader new take word during.', 2, 11),
('Lay training out.', 1, 12),
('Whom enough federal pattern always message free.', 3, 13),
('Near food mission paper lot.', 2, 14),
('Career occur stand up hot everybody.', 2, 15),
('Travel dinner similar difference.', 1, 16),
('Force choice list positive program.', 5, 17),
('Yourself sea capital as.', 1, 18),
('Teach office be address push.', 5, 19),
('Drive agree third add.', 4, 20),
('Public management quality take improve measure author.', 2, 21),
('Fear realize thousand street history stay somebody.', 4, 22),
('Become yeah court serious reveal.', 2, 23),
('Center national series.', 2, 24),
('Left size focus six occur upon.', 5, 25),
('Force own not boy.', 1, 26),
('Start million social.', 3, 27),
('Send table system.', 3, 28),
('Finally race city piece wind civil.', 1, 29),
('Music moment establish government special school participant.', 3, 30),
('Character turn bill high.', 1, 31),
('Especially check garden people pull.', 3, 32),
('Card increase argue when.', 5, 33),
('Poor fish only employee ball responsibility page.', 1, 34),
('Consider land piece and take customer check.', 3, 35),
('Some clearly at difference gas.', 5, 36),
('Other difficult according Democrat for history above high.', 1, 37),
('Central sport whom space according explain off police.', 1, 38),
('Run whether save body easy.', 5, 39),
('Among everything worker.', 1, 40),
('Him home happen between kitchen.', 1, 1),
('Put spring court wrong out visit there black.', 2, 2),
('Material learn seem.', 3, 3),
('Store air ok family onto ago interesting today.', 1, 4),
('Fly remember business our reason prevent.', 1, 5),
('Fight boy he group.', 3, 6),
('Safe movement protect.', 1, 7),
('Amount heart foot old beyond able.', 2, 8),
('Brother suddenly again leader before.', 5, 9),
('Get three article list ready.', 5, 10),
('Paper less notice threat writer.', 2, 11),
('Prevent customer future increase.', 2, 12),
('No beat nor law education own.', 4, 13),
('Fund this anyone song full.', 4, 14),
('Would structure act new seek moment question.', 3, 15),
('Sure bit law strategy black probably hear glass.', 4, 16),
('Operation claim road subject business a.', 4, 17),
('Trial performance back material interview change six.', 1, 18),
('Through health across up American answer.', 4, 19),
('Across fish try size maybe walk out.', 4, 20),
('Together represent wall ok life fight despite.', 1, 21),
('Ability seek painting several ask.', 4, 22),
('Development firm those oil.', 4, 23),
('Have themselves wonder yeah white dark.', 2, 24),
('Child unit environmental Congress decide pass fly.', 3, 25),
('Because if gun option skin lawyer.', 1, 26),
('Ability size part call.', 5, 27),
('Fire however risk report listen act them.', 1, 28),
('Of threat authority measure moment.', 5, 29),
('Instead gas center last spend try later.', 5, 30),
('Window Congress east relate particular letter west avoid.', 2, 31),
('Important join throw strategy poor.', 5, 32),
('Key already sense.', 5, 33),
('Upon lot them as network.', 1, 34),
('Pull medical face method task until.', 1, 35),
('One series song southern form make project major.', 2, 36),
('Certain long identify office life exactly religious.', 1, 37),
('Success firm senior nothing.', 3, 38),
('Address attack charge.', 2, 39),
('Majority college each daughter.', 2, 40),
('Sure moment partner law station guess probably card.', 4, 1),
('Program like ahead woman thank carry.', 4, 2),
('Heart goal price economic.', 3, 3),
('Stand lose lay according style health model.', 2, 4),
('Thought government point college trip door difference.', 1, 5),
('Painting inside fact couple yeah.', 1, 6),
('Film cell chair painting firm.', 2, 7),
('Cost size hand military someone yet.', 5, 8),
('Kid figure decade crime card.', 4, 9),
('Rest economy community.', 2, 10),
('Theory conference draw tell organization artist.', 2, 11),
('Argue site end education side.', 5, 12),
('Statement attention red knowledge development.', 1, 13),
('Sure audience record there run Mr position.', 2, 14),
('Treatment notice lot listen training nor kind force.', 3, 15),
('Note represent every.', 2, 16),
('Particularly probably draw many next bill turn serve.', 5, 17),
('Nature threat again key strong bag.', 3, 18),
('Fish near fast significant color.', 1, 19),
('Fact forward ball growth could same even.', 3, 20),
('Region name stuff government form serve box.', 4, 21),
('Truth measure charge act quite.', 3, 22),
('Sing consider face fire.', 3, 23),
('Word choose red meet.', 4, 24),
('Treat always friend sound wind ready.', 1, 25),
('Rate method table myself social military.', 4, 26),
('Trial plant kid military report can picture.', 2, 27),
('Popular everyone tax policy perhaps under imagine responsibility.', 4, 28),
('Life first once since.', 5, 29),
('Stay state great theory image choice.', 4, 30),
('Return seek whatever southern.', 2, 31),
('Example oil trade process hour history.', 4, 32),
('Knowledge play rich need include much.', 3, 33),
('Beautiful character economic trial.', 3, 34),
('Firm free back boy.', 4, 35),
('Baby message her pay room rest Republican.', 5, 36),
('Animal he position wife suggest dog.', 5, 37),
('Fire just another Republican figure account account.', 5, 38),
('Base challenge book quality agency.', 4, 39),
('Threat everybody return per analysis.', 5, 40),
('Alone give decide put.', 5, 1),
('Process ok for rather.', 1, 2),
('But study foreign effect him.', 3, 3),
('Hit mission race.', 3, 4),
('Worker ball first medical.', 2, 5),
('Buy meeting anyone second.', 4, 6),
('Record green successful indeed record choose.', 1, 7),
('Water west statement whose concern leg.', 3, 8),
('Scene beyond nature back suffer.', 1, 9),
('Where identify deal participant upon note.', 3, 10);

insert into article_like
	(client_id, article_id)
values
(1, 1),
(2, 1),
(3, 1),
(4, 1),
(5, 1),
(6, 1),
(7, 1),
(8, 1),
(9, 1),
(10, 1),
(11, 1),
(12, 1),
(13, 1),
(14, 1),
(15, 1),
(16, 1),
(17, 1),
(18, 1),
(19, 1),
(20, 1),
(21, 1),
(22, 1),
(23, 1),
(24, 1),
(25, 1),
(26, 1),
(27, 1),
(28, 1),
(29, 1),
(30, 1),
(31, 1),
(32, 1),
(33, 1),
(34, 1),
(35, 1),
(36, 1),
(37, 1),
(38, 1),
(39, 1),
(40, 1),
(1, 2),
(2, 2),
(3, 2),
(4, 2),
(5, 2),
(6, 2),
(7, 2),
(8, 2),
(9, 2),
(10, 2),
(11, 2),
(12, 2),
(13, 2),
(14, 2),
(15, 2),
(16, 2),
(17, 2),
(18, 2),
(19, 2),
(20, 2),
(21, 2),
(22, 2),
(23, 2),
(24, 2),
(25, 2),
(26, 2),
(27, 2),
(28, 2),
(29, 2),
(30, 2),
(31, 2),
(32, 2),
(33, 2),
(34, 2),
(35, 2),
(36, 2),
(37, 2),
(38, 2),
(39, 2),
(40, 2),
(1, 3),
(2, 3),
(3, 3),
(4, 3),
(5, 3),
(6, 3),
(7, 3),
(8, 3),
(9, 3),
(10, 3),
(11, 3),
(12, 3),
(13, 3),
(14, 3),
(15, 3),
(16, 3),
(17, 3),
(18, 3),
(19, 3),
(20, 3),
(21, 3),
(22, 3),
(23, 3),
(24, 3),
(25, 3),
(26, 3),
(27, 3),
(28, 3),
(29, 3),
(30, 3),
(31, 3),
(32, 3),
(33, 3),
(34, 3),
(35, 3),
(36, 3),
(37, 3),
(38, 3),
(39, 3),
(40, 3),
(1, 4),
(2, 4),
(3, 4),
(4, 4),
(5, 4),
(6, 4),
(7, 4),
(8, 4),
(9, 4),
(10, 4),
(11, 4),
(12, 4),
(13, 4),
(14, 4),
(15, 4),
(16, 4),
(17, 4),
(18, 4),
(19, 4),
(20, 4),
(21, 4),
(22, 4),
(23, 4),
(24, 4),
(25, 4),
(26, 4),
(27, 4),
(28, 4),
(29, 4),
(30, 4),
(31, 4),
(32, 4),
(33, 4),
(34, 4),
(35, 4),
(36, 4),
(37, 4),
(38, 4),
(39, 4),
(40, 4),
(1, 5),
(2, 5),
(3, 5),
(4, 5),
(5, 5),
(6, 5),
(7, 5),
(8, 5),
(9, 5),
(10, 5),
(11, 5),
(12, 5),
(13, 5),
(14, 5),
(15, 5),
(16, 5),
(17, 5),
(18, 5),
(19, 5),
(20, 5),
(21, 5),
(22, 5),
(23, 5),
(24, 5),
(25, 5),
(26, 5),
(27, 5),
(28, 5),
(29, 5),
(30, 5),
(31, 5),
(32, 5),
(33, 5),
(34, 5),
(35, 5),
(36, 5),
(37, 5),
(38, 5),
(39, 5),
(40, 5);

insert into product
	(name, description, price, client_id)
values
('Woman', 'Physical weight month tell occur of kind.', 671.87, 1),
('Program', 'How business star language heavy carry always.', 238.34, 2),
('Together', 'Campaign front believe instead discussion.', 773.45, 3),
('Toward', 'Major focus garden city.', 957.47, 4),
('Religious', 'Somebody include Mr attention.', 427.15, 5),
('American', 'Serve war reduce tell such take say.', 785.38, 1),
('Idea', 'Top later still rich really realize fine.', 354.15, 2),
('Some', 'Somebody show its cost process claim different.', 390.41, 3),
('Perhaps', 'Blue expert hotel note institution.', 749.19, 4),
('Child', 'Carry scene strategy little ever scene relate.', 595.64, 5),
('Well', 'Nature specific artist back for.', 487.54, 1),
('Much', 'Enter she main represent.', 922.95, 2),
('At', 'Eye manage happen election talk.', 107.35, 3),
('Reveal', 'Suggest myself president assume establish finish.', 575.31, 4),
('Growth', 'Be six task fire side contain business.', 140.6, 5),
('Use', 'By reflect next cut memory.', 749.8, 1),
('Court', 'Drop drive process door.', 409.59, 2),
('For', 'Hit other win nothing mind must.', 559.68, 3),
('Which', 'Beyond year lawyer main history concern.', 705.72, 4),
('Local', 'Wish draw method more half nation despite.', 385.62, 5),
('Full', 'Form ground would admit sea yet.', 922.16, 1),
('Brother', 'Thank sit threat join short its.', 418.3, 2),
('That', 'Bit mission report goal sell determine.', 872.34, 3),
('Bill', 'Then use prepare individual.', 391.97, 4),
('Father', 'Entire almost beautiful benefit road.', 947.83, 5),
('Somebody', 'Scientist interview language know city.', 798.5, 1),
('Recently', 'Conference age language choice final exactly.', 406.72, 2),
('Use', 'Middle of arrive tax old college main.', 219.91, 3),
('Myself', 'Choose response pay very level.', 836.64, 4),
('Anyone', 'Future cut technology cause. Inside ground step.', 929.33, 5),
('Relations', 'Subject identify president fall.', 793.69, 1),
('Executive', 'Seat art wonder president step PM read.', 478.52, 2),
('Everythin', 'Material leader Congress positive.', 789.41, 3),
('Similar', 'Buy million ground political leave.', 763.53, 4),
('Power', 'Serve consider professional.', 110.98, 5),
('Listen', 'For once sign new close.', 168.37, 1),
('Yourself', 'Shake today response system save glass.', 20.79, 2),
('Left', 'Close shoulder need century.', 361.22, 3),
('Nor', 'Consumer go still key real traditional over.', 64.0, 4),
('Floor', 'Hard picture down there maybe difference eye.', 447.81, 5),
('Member', 'A professional service it.', 677.21, 1),
('Special', 'Training enter either that option ever least Mr.', 528.19, 2),
('Do', 'Contain want they song.', 171.77, 3),
('Weight', 'Situation call carry follow. Skin its career.', 955.39, 4),
('North', 'Never nothing far industry.', 459.9, 5),
('Possible', 'I season black current.', 154.56, 1),
('View', 'Test discuss heart where western become.', 293.94, 2),
('Like', 'Fill every resource job fight lawyer.', 81.63, 3),
('Radio', 'Place glass wish mean get case contain.', 762.37, 4),
('Career', 'Experience image discuss parent unit director.', 101.67, 5),
('Important', 'Room she simply night require.', 572.51, 1),
('Himself', 'She other direction house society back.', 358.75, 2),
('Forget', 'Paper million head nearly.', 899.46, 3),
('Blood', 'Condition away former tend soldier.', 471.53, 4),
('Center', 'Season impact bar able policy peace.', 575.94, 5),
('Break', 'Whole phone system.', 588.63, 1),
('Step', 'Type fall wind machine road network style.', 199.41, 2),
('Safe', 'Conference save easy.', 277.08, 3),
('Beautiful', 'Process task establish model.', 192.47, 4),
('Someone', 'City nothing meeting increase.', 566.68, 5),
('Like', 'Industry feeling letter speech source.', 761.07, 1),
('Each', 'Daughter appear condition director strong.', 313.51, 2),
('Mr', 'Degree federal detail computer past.', 736.89, 3),
('Test', 'Almost improve one while hundred.', 294.42, 4),
('Hospital', 'Small small dog usually exactly hope.', 88.85, 5),
('Some', 'Leader evidence represent enter professional.', 644.05, 1),
('Interesti', 'Must cause physical expert onto.', 130.99, 2),
('Local', 'Like my accept law plant begin.', 612.83, 3),
('Suddenly', 'Cup already yeah their.', 227.93, 4),
('What', 'Hear recent like represent. Who of wonder series.', 202.42, 5),
('Become', 'Article month leader pull.', 983.45, 1),
('Power', 'Real together south wonder law part or.', 118.65, 2),
('Method', 'Smile help morning office whatever take color.', 228.13, 3),
('Than', 'Even discussion minute change force state human.', 795.9, 4),
('Compare', 'Role pressure sit.', 713.37, 5),
('Experienc', 'Trial move site new capital money piece response.', 259.36, 1),
('Down', 'Voice possible environment.', 223.9, 2),
('Bar', 'Own send themselves.', 227.95, 3),
('Serve', 'Who individual another coach on care idea action.', 268.11, 4),
('Protect', 'Practice hear follow bad design industry return.', 367.25, 5),
('Avoid', 'Personal alone he fight expect agent born.', 658.35, 1),
('Lose', 'Resource bag entire against appear decide choose.', 172.43, 2),
('For', 'Send executive kind program yet factor image.', 164.33, 3),
('Product', 'Mean study try look action discussion.', 149.54, 4),
('Network', 'Create PM concern behind author single building.', 224.48, 5),
('Space', 'None think answer its send agent.', 446.69, 1),
('Just', 'Back agree vote.', 460.69, 2),
('Evidence', 'Determine do up attention enough plant.', 344.95, 3),
('Career', 'Player window everything husband.', 565.73, 4),
('Rock', 'Environmental player soon know.', 718.45, 5),
('Learn', 'Assume I old research draw form.', 925.41, 1),
('Possible', 'None serious choice join institution.', 151.77, 2),
('Describe', 'Body exist design law heart close.', 422.64, 3),
('Win', 'About imagine material just animal network.', 91.37, 4),
('Inside', 'Behind foot travel bring role carry month.', 484.97, 5),
('Task', 'Phone wife small start open so.', 551.84, 1),
('Might', 'Might throw air will civil see.', 644.17, 2),
('Receive', 'Analysis speech contain less source.', 816.13, 3),
('Ask', 'Especially price both PM chair age exactly.', 830.7, 4),
('Nor', 'Program share morning job green question.', 81.28, 5),
('Situation', 'Defense modern chair stuff somebody sell if drug.', 258.6, 1),
('Condition', 'Tax since vote discuss.', 525.05, 2),
('Serve', 'Particularly husband together economy range wall.', 428.83, 3),
('Resource', 'Management room smile.', 103.28, 4),
('Nature', 'Per popular exist material next.', 904.69, 5),
('Available', 'Music notice low common.', 590.82, 1),
('Toward', 'Between really baby future.', 707.77, 2),
('Anything', 'Level gun beyond speech tend age issue.', 734.58, 3),
('Cost', 'Individual growth toward unit. With top music.', 571.92, 4),
('Focus', 'Assume Mr war receive century health glass.', 765.09, 5),
('Bag', 'Thing within such minute floor image.', 416.06, 1),
('Interview', 'Call husband music career year improve.', 485.69, 2),
('Camera', 'Camera happy foreign.', 521.55, 3),
('Method', 'Capital recently music food parent.', 301.05, 4),
('Western', 'Surface boy adult decide again travel throw.', 221.43, 5),
('Inside', 'Fire many paper.', 980.73, 1),
('Doctor', 'Strategy however item buy key.', 564.51, 2),
('Bank', 'Trade natural senior history anything white.', 192.39, 3),
('Town', 'And growth approach business record check.', 660.55, 4),
('Type', 'We hold decision TV perform group.', 583.23, 5),
('Lot', 'Your meet source cost against rock green person.', 552.03, 1),
('Newspaper', 'Environmental with appear from.', 211.53, 2),
('Religious', 'Entire role television recently right.', 684.03, 3),
('Buy', 'Hand third pretty like finish threat fire.', 416.42, 4),
('Reflect', 'Ask training reflect official read get it own.', 393.22, 5),
('Road', 'Ever project worry address better test serious.', 760.38, 1),
('Professio', 'Place prepare others measure respond five than.', 335.64, 2),
('Support', 'Conference training admit. Middle friend him say.', 787.53, 3),
('Attack', 'Teacher available partner particular exist.', 80.64, 4),
('Including', 'Economy mission later base relate American wall.', 939.0, 5),
('Purpose', 'Television out newspaper child have draw.', 67.45, 1),
('People', 'Someone hospital edge job.', 620.34, 2),
('Clear', 'Lawyer owner somebody next him defense.', 148.35, 3),
('However', 'Politics fire result end as big social.', 825.52, 4),
('Move', 'Stuff better anyone film culture.', 391.07, 5),
('Best', 'No force sometimes. Gun push her share.', 694.77, 1),
('Pretty', 'Decision just avoid. Hard organization school.', 544.76, 2),
('Grow', 'Break single listen daughter.', 489.04, 3),
('Exactly', 'Should pressure meeting until.', 733.72, 4),
('Increase', 'Amount by animal call.', 934.25, 5),
('Pay', 'According any picture throughout country since.', 970.03, 1),
('Certainly', 'Next success raise oil budget amount life.', 668.45, 2),
('Able', 'Son heavy than.', 609.03, 3),
('Level', 'Six race girl trial none.', 900.52, 4),
('Image', 'Very know baby increase green occur above.', 913.86, 5),
('Less', 'Put during moment explain.', 136.55, 1),
('Father', 'Media difference message yard stage it serious.', 410.03, 2),
('Everythin', 'Forward benefit property.', 349.29, 3),
('Fact', 'Well tax significant week look sure.', 981.79, 4),
('Sound', 'Of write want result face law.', 380.94, 5);

insert into product_like
	(client_id, product_id)
values
(1, 1),
(2, 1),
(3, 1),
(4, 1),
(5, 1),
(6, 1),
(7, 1),
(8, 1),
(9, 1),
(10, 1),
(11, 1),
(12, 1),
(13, 1),
(14, 1),
(15, 1),
(16, 1),
(17, 1),
(18, 1),
(19, 1),
(20, 1),
(21, 1),
(22, 1),
(23, 1),
(24, 1),
(25, 1),
(26, 1),
(27, 1),
(28, 1),
(29, 1),
(30, 1),
(31, 1),
(32, 1),
(33, 1),
(34, 1),
(35, 1),
(36, 1),
(37, 1),
(38, 1),
(39, 1),
(40, 1),
(1, 2),
(2, 2),
(3, 2),
(4, 2),
(5, 2),
(6, 2),
(7, 2),
(8, 2),
(9, 2),
(10, 2),
(11, 2),
(12, 2),
(13, 2),
(14, 2),
(15, 2),
(16, 2),
(17, 2),
(18, 2),
(19, 2),
(20, 2),
(21, 2),
(22, 2),
(23, 2),
(24, 2),
(25, 2),
(26, 2),
(27, 2),
(28, 2),
(29, 2),
(30, 2),
(31, 2),
(32, 2),
(33, 2),
(34, 2),
(35, 2),
(36, 2),
(37, 2),
(38, 2),
(39, 2),
(40, 2),
(1, 3),
(2, 3),
(3, 3),
(4, 3),
(5, 3),
(6, 3),
(7, 3),
(8, 3),
(9, 3),
(10, 3),
(11, 3),
(12, 3),
(13, 3),
(14, 3),
(15, 3),
(16, 3),
(17, 3),
(18, 3),
(19, 3),
(20, 3),
(21, 3),
(22, 3),
(23, 3),
(24, 3),
(25, 3),
(26, 3),
(27, 3),
(28, 3),
(29, 3),
(30, 3),
(31, 3),
(32, 3),
(33, 3),
(34, 3),
(35, 3),
(36, 3),
(37, 3),
(38, 3),
(39, 3),
(40, 3),
(1, 4),
(2, 4),
(3, 4),
(4, 4),
(5, 4),
(6, 4),
(7, 4),
(8, 4),
(9, 4),
(10, 4),
(11, 4),
(12, 4),
(13, 4),
(14, 4),
(15, 4),
(16, 4),
(17, 4),
(18, 4),
(19, 4),
(20, 4),
(21, 4),
(22, 4),
(23, 4),
(24, 4),
(25, 4),
(26, 4),
(27, 4),
(28, 4),
(29, 4),
(30, 4),
(31, 4),
(32, 4),
(33, 4),
(34, 4),
(35, 4),
(36, 4),
(37, 4),
(38, 4),
(39, 4),
(40, 4),
(1, 5),
(2, 5),
(3, 5),
(4, 5),
(5, 5),
(6, 5),
(7, 5),
(8, 5),
(9, 5),
(10, 5),
(11, 5),
(12, 5),
(13, 5),
(14, 5),
(15, 5),
(16, 5),
(17, 5),
(18, 5),
(19, 5),
(20, 5),
(21, 5),
(22, 5),
(23, 5),
(24, 5),
(25, 5),
(26, 5),
(27, 5),
(28, 5),
(29, 5),
(30, 5),
(31, 5),
(32, 5),
(33, 5),
(34, 5),
(35, 5),
(36, 5),
(37, 5),
(38, 5),
(39, 5),
(40, 5);

insert into product_comment
	(content, product_id, client_id)
values
('Process total once democratic.', 5, 1),
('Job woman never hear ever investment might.', 2, 2),
('Pass plan heavy while today walk professional.', 1, 3),
('One both full war person east.', 5, 4),
('Soon never them dog.', 3, 5),
('Activity law more score feel.', 2, 6),
('Project above four different west.', 2, 7),
('Share million whether involve.', 5, 8),
('Minute best wear cover.', 5, 9),
('Hope hour member certainly.', 3, 10),
('Building save team walk.', 4, 11),
('Begin its necessary history.', 2, 12),
('Officer benefit around road fly involve.', 5, 13),
('He performance term measure.', 4, 14),
('Around there board.', 1, 15),
('Along bank center step.', 3, 16),
('Likely morning case statement member who better.', 1, 17),
('Space back education media laugh door.', 2, 18),
('Establish tend tree sense meeting.', 2, 19),
('Pm former third have manager now scientist.', 5, 20),
('Seven smile political nor development continue.', 3, 21),
('Citizen too by or beat kitchen.', 1, 22),
('Compare picture not another give night.', 4, 23),
('Effect probably none song everybody.', 5, 24),
('Collection song call tonight.', 5, 25),
('Real back man upon street happy.', 4, 26),
('Night strategy guess.', 2, 27),
('This away bit peace them ask night end.', 3, 28),
('Ever table water bad notice authority action guy.', 5, 29),
('Condition cultural myself tell.', 1, 30),
('Thus success leave food.', 5, 31),
('Likely have alone stay.', 1, 32),
('Choice join when piece large fact economic.', 3, 33),
('Dinner else deal final claim leg speech.', 2, 34),
('Student most music around form rather oil.', 4, 35),
('Them why career simply price.', 3, 36),
('Form man style third take her later.', 3, 37),
('Man degree yes morning.', 2, 38),
('Weight floor serious whose design catch.', 4, 39),
('Mind inside perform safe most.', 4, 40),
('Her sense blood expert bill form special.', 4, 1),
('Himself remember measure hair nor be.', 3, 2),
('Care describe field much receive.', 4, 3),
('Car citizen far general you this art.', 5, 4),
('Former full new though into.', 4, 5),
('Their east house family.', 4, 6),
('Responsibility rich people fund.', 2, 7),
('Understand table head significant campaign.', 3, 8),
('Though range Republican rather road.', 1, 9),
('Life the risk six check guy speech.', 5, 10),
('Break attack response study he positive.', 4, 11),
('Goal out run from about.', 2, 12),
('Charge walk defense hot.', 1, 13),
('Should change college bar life officer without.', 2, 14),
('Along make perhaps wonder.', 2, 15),
('Director option teach control event wonder particularly.', 1, 16),
('Yet notice sense of.', 4, 17),
('Development management possible less real commercial.', 3, 18),
('Herself statement common people design.', 4, 19),
('Stay party hour painting.', 2, 20),
('Particular against scene attention American size.', 3, 21),
('Break debate draw Congress.', 5, 22),
('Know seem I arm range teach.', 3, 23),
('Cultural together heavy reduce major sing movie action.', 3, 24),
('Threat leader detail everything explain.', 4, 25),
('Different board perhaps safe learn.', 1, 26),
('Network day past upon.', 1, 27),
('Feeling research for so strong challenge book.', 2, 28),
('See data increase learn sport.', 4, 29),
('Card service unit financial the create realize may.', 1, 30),
('Develop indicate parent executive city professor challenge yard.', 3, 31),
('Hard ok on.', 2, 32),
('Run reality money vote pressure black.', 3, 33),
('Beautiful little point nearly front speak.', 5, 34),
('Study write left happy card attorney behind.', 3, 35),
('Manage black community agree radio.', 1, 36),
('Republican sit there book.', 4, 37),
('Must dream concern teach thought approach professor.', 3, 38),
('Young kid different however.', 5, 39),
('Right scientist answer community act interest long.', 2, 40),
('Wait concern recent my I among.', 4, 1),
('Show now away wait admit.', 5, 2),
('Operation until player condition.', 2, 3),
('Those smile system fine American give.', 3, 4),
('Than mean hard miss country night.', 3, 5),
('Daughter it space at property surface.', 5, 6),
('Even manage inside government drive green.', 2, 7),
('Special daughter technology treatment evidence.', 5, 8),
('Agency type consumer personal natural month.', 4, 9),
('Read society country range lot recognize.', 3, 10),
('Hair study century whom daughter wrong.', 5, 11),
('A surface true leg.', 5, 12),
('Up there organization usually the.', 2, 13),
('Officer significant age.', 3, 14),
('May carry significant together record wide realize member.', 4, 15),
('True attack win across seven three follow chair.', 4, 16),
('Spend training free.', 2, 17),
('North necessary beyond color reason.', 5, 18),
('Live and generation.', 5, 19),
('Owner free simple suffer officer assume.', 5, 20),
('Stuff stuff factor line live production success.', 3, 21),
('Development say without hard.', 1, 22),
('Relationship standard create business stand.', 2, 23),
('However should a if under risk.', 5, 24),
('Stop after behavior big good.', 3, 25),
('Create above receive reflect teach candidate.', 3, 26),
('Generation up ten partner officer bill.', 3, 27),
('Information cover happy head.', 5, 28),
('Live family voice toward available do simple.', 1, 29),
('Arm involve order radio quality provide.', 4, 30),
('Travel doctor card reason your its others.', 4, 31),
('Agent indicate begin power.', 4, 32),
('Couple adult face skin hair.', 5, 33),
('Him help some yes choose Republican ok.', 2, 34),
('Middle here defense enough purpose whom.', 3, 35),
('Recently door travel wrong loss.', 2, 36),
('Sea change young able.', 5, 37),
('Quite other buy.', 3, 38),
('Where case soon scene.', 5, 39),
('Though international visit effort agree.', 2, 40),
('Executive both then matter employee.', 1, 1),
('Agency return future meeting.', 4, 2),
('Spring effect short cup although office report.', 1, 3),
('Form all reason challenge.', 3, 4),
('Each top sea result.', 1, 5),
('Thought change including since collection political.', 3, 6),
('Often discover fire safe.', 5, 7),
('Success his high day catch continue perhaps.', 4, 8),
('Kid good reveal main movement plant play war.', 4, 9),
('Maybe goal her than if choice.', 1, 10),
('Field pattern candidate way character.', 4, 11),
('Bag environmental one site ground.', 5, 12),
('Away present right young imagine staff happy.', 2, 13),
('Nor late suddenly choose of through.', 1, 14),
('Ok stuff practice issue the doctor perform.', 2, 15),
('Whom many alone organization.', 1, 16),
('Its page thus address this cell.', 1, 17),
('Someone reality capital street food pay.', 5, 18),
('Opportunity thousand your range process operation.', 3, 19),
('What hard trouble begin response.', 1, 20),
('Throw could happen be.', 3, 21),
('Culture husband me group method lose until.', 4, 22),
('Require foreign everything listen be culture.', 4, 23),
('Believe since sometimes speech as we.', 2, 24),
('Growth world shoulder buy.', 2, 25),
('Lot cause mission beautiful participant including anyone.', 5, 26),
('Method special deal today.', 2, 27),
('Could deal thought operation until question word.', 5, 28),
('Shake bank many early three its.', 1, 29),
('Good southern attention chair.', 5, 30),
('Large state forget identify two them ground.', 1, 31),
('They employee discussion expect.', 4, 32),
('Plant sound table me million.', 3, 33),
('Pick baby sometimes certainly nothing.', 5, 34),
('Let factor wall free big enter place.', 3, 35),
('Our force relate.', 3, 36),
('Color various beat.', 5, 37),
('Young begin hear support organization deal baby.', 5, 38),
('Either reflect performance others perform service leader.', 5, 39),
('Through expect note conference theory happy concern.', 5, 40),
('Of give child firm speech remember.', 4, 1),
('Significant decide side PM win cultural decade.', 5, 2),
('Have age movement quickly between myself.', 4, 3),
('Together beat join box along grow approach.', 2, 4),
('Whether mention four.', 3, 5),
('Bad style fish everyone some.', 4, 6),
('Economy both miss force with.', 1, 7),
('Safe opportunity economy large significant building.', 3, 8),
('Laugh very truth office technology with.', 5, 9),
('Color story that amount doctor line easy.', 3, 10),
('Decision happen yard west lawyer first cell.', 2, 11),
('Measure bill prove car.', 5, 12),
('Call even recently despite son.', 2, 13),
('Material statement not minute finish along identify pay.', 1, 14),
('Southern especially friend plan accept.', 5, 15),
('Second side finally matter care.', 1, 16),
('Stock southern loss religious live.', 1, 17),
('Stay technology range network scene plant.', 2, 18),
('Across vote human these task wall difficult.', 2, 19),
('Leg others indicate important represent market hour.', 3, 20),
('Partner hair by leave despite.', 2, 21),
('Trial own size instead look character recent.', 1, 22),
('Wall each commercial carry senior Mr.', 3, 23),
('Certain then model different degree.', 5, 24),
('Bad college structure share those.', 4, 25),
('Present school others general work professor sound health.', 2, 26),
('Will heavy under consider only speak I.', 5, 27),
('Recently lose morning age name.', 3, 28),
('Several myself bit nor sister during.', 1, 29),
('Professional parent boy issue reality nature.', 1, 30),
('Stay individual her line rest major.', 4, 31),
('Student present born.', 4, 32),
('Take bed collection.', 2, 33),
('Always herself stock lot strong act remember.', 3, 34),
('Perform affect including leave heavy player vote.', 4, 35),
('His prove method home.', 3, 36),
('Focus strong start record well.', 2, 37),
('Future again heart nor nothing price design.', 1, 38),
('Show to second but across magazine national.', 2, 39),
('Money investment guess.', 5, 40),
('Woman care other trial.', 3, 1),
('Center though safe despite way follow.', 4, 2),
('Want situation surface plant.', 1, 3),
('Number still feeling human pass state majority.', 1, 4),
('Decide fear peace two early put above large.', 2, 5),
('Such source compare carry.', 2, 6),
('Seat color leg father design.', 2, 7),
('Behavior unit able employee maybe.', 3, 8),
('End source share nor Democrat approach.', 2, 9),
('Also decade compare girl thing center radio.', 1, 10),
('Appear tree foreign tonight others.', 5, 11),
('When recent too daughter democratic.', 5, 12),
('Key myself three join picture street win.', 3, 13),
('Nice this citizen their.', 3, 14),
('Soon continue mention it young successful little drive.', 2, 15),
('History political final form high candidate prevent fight.', 4, 16),
('Mother worry analysis up.', 3, 17),
('Mr certain develop seem act.', 2, 18),
('Occur say middle moment member.', 1, 19),
('This white walk.', 1, 20),
('Wall avoid guess hotel.', 4, 21),
('Can because language.', 4, 22),
('Where purpose special student.', 4, 23),
('Take reach career professional Democrat skin.', 4, 24),
('Act tree reality kid main.', 5, 25),
('First establish Mrs fall dream final.', 1, 26),
('Career move instead mission personal energy.', 5, 27),
('Number region total dinner.', 5, 28),
('Many meet never crime.', 5, 29),
('Interest beyond mouth every official.', 4, 30),
('Mention study baby positive fight light.', 2, 31),
('Agency majority themselves major.', 4, 32),
('Simply hard away laugh and catch.', 5, 33),
('Campaign realize Democrat investment idea.', 5, 34),
('Send identify Democrat management money reduce.', 4, 35),
('Manager accept wonder reduce improve western smile mind.', 3, 36),
('Laugh bad figure pay resource market who health.', 3, 37),
('Data bar measure others weight stuff.', 1, 38),
('Accept page fine course treat anyone morning.', 5, 39),
('Education market might tend.', 2, 40),
('Draw occur full us maybe cell explain trade.', 1, 1),
('Tonight fight wear plan reveal focus.', 1, 2),
('None him learn provide himself.', 2, 3),
('Boy suffer leader book through message.', 4, 4),
('Successful matter maybe general talk and charge.', 3, 5),
('Father leg soon.', 4, 6),
('Several clearly oil whether.', 5, 7),
('Election him administration go five.', 4, 8),
('Create road talk happen character.', 5, 9),
('Carry education ready member according property.', 1, 10),
('Kind quickly two similar heavy treatment pretty.', 3, 11),
('Action including general continue learn catch decade herself.', 2, 12),
('Live nature type yeah talk meeting far.', 5, 13),
('Into challenge there tax.', 2, 14),
('Including half election turn hear.', 2, 15),
('Agree owner ten dream.', 4, 16),
('Wonder American middle ok task.', 4, 17),
('Its note from between policy piece eat strong.', 1, 18),
('Tell opportunity challenge second.', 4, 19),
('Talk lose sister.', 3, 20),
('Major establish form professional.', 2, 21),
('Computer number poor daughter.', 4, 22),
('Perhaps military almost can.', 3, 23),
('Story course production thing and woman.', 3, 24),
('Interview either must interest along pick.', 5, 25),
('Of by government certainly without.', 1, 26),
('Never at ago respond nothing.', 4, 27),
('Be quality so clear rate style.', 1, 28),
('Local perhaps police when.', 1, 29),
('How week whose party.', 4, 30),
('The simply stock anyone subject chance.', 4, 31),
('As management music major same.', 2, 32),
('Term citizen deep war tax no.', 2, 33),
('Mr book card admit ever official finish.', 4, 34),
('Local factor piece thing language cause hospital.', 5, 35),
('Own no part several.', 1, 36),
('Left hotel base consider wall participant late.', 3, 37),
('Address bank seat nation.', 2, 38),
('Old term manager person key great late.', 2, 39),
('Place through information someone air.', 4, 40),
('Yet physical than stand.', 3, 1),
('By carry listen account story.', 3, 2),
('Those population necessary their property claim.', 3, 3),
('Issue study up agent main myself.', 2, 4),
('Professional I product under response boy than.', 2, 5),
('Much they born official here agree.', 5, 6),
('Gun still type.', 3, 7),
('Teacher member face movement land determine attention once.', 2, 8),
('Top message two question amount.', 1, 9),
('Customer take body different production.', 5, 10),
('Sort decision near.', 3, 11),
('Strong answer myself check treat.', 5, 12),
('Word wide along.', 2, 13),
('Morning expect win.', 4, 14),
('Successful sort list deal reality these cut difficult.', 5, 15),
('Hit attention arm direction evidence majority call.', 1, 16),
('Must face sound.', 1, 17),
('Consider ability film song possible minute this.', 3, 18),
('Bar through light station sure away.', 4, 19),
('Director arrive course identify key those lot.', 4, 20);

insert into tag
	(name)
values
('0001'),
('0002'),
('0003'),
('0004'),
('0005'),
('0006'),
('0007'),
('0008'),
('0009'),
('0010'),
('0011'),
('0012'),
('0013'),
('0014'),
('0015'),
('0016'),
('0017'),
('0018'),
('0019'),
('0020'),
('0021'),
('0022'),
('0023'),
('0024'),
('0025'),
('0026'),
('0027'),
('0028'),
('0029'),
('0030'),
('0031'),
('0032'),
('0033'),
('0034'),
('0035'),
('0036'),
('0037'),
('0038'),
('0039'),
('0040');

insert into product_tag
	(tag_id, product_id)
values
(1, 1),
(2, 2),
(3, 3),
(4, 4),
(5, 5),
(6, 6),
(7, 7),
(8, 8),
(9, 9),
(10, 10),
(11, 11),
(12, 12),
(13, 13),
(14, 14),
(15, 15),
(16, 16),
(17, 17),
(18, 18),
(19, 19),
(20, 20),
(21, 21),
(22, 22),
(23, 23),
(24, 24),
(25, 25),
(26, 26),
(27, 27),
(28, 28),
(29, 29),
(30, 30),
(31, 31),
(32, 32),
(33, 33),
(34, 34),
(35, 35),
(36, 36),
(37, 37),
(38, 38),
(39, 39),
(40, 40),
(1, 41),
(2, 42),
(3, 43),
(4, 44),
(5, 45),
(6, 46),
(7, 47),
(8, 48),
(9, 49),
(10, 50),
(11, 51),
(12, 52),
(13, 53),
(14, 54),
(15, 55),
(16, 56),
(17, 57),
(18, 58),
(19, 59),
(20, 60),
(21, 61),
(22, 62),
(23, 63),
(24, 64),
(25, 65),
(26, 66),
(27, 67),
(28, 68),
(29, 69),
(30, 70),
(31, 71),
(32, 72),
(33, 73),
(34, 74),
(35, 75),
(36, 76),
(37, 77),
(38, 78),
(39, 79),
(40, 80),
(1, 81),
(2, 82),
(3, 83),
(4, 84),
(5, 85),
(6, 86),
(7, 87),
(8, 88),
(9, 89),
(10, 90),
(11, 91),
(12, 92),
(13, 93),
(14, 94),
(15, 95),
(16, 96),
(17, 97),
(18, 98),
(19, 99),
(20, 100),
(21, 101),
(22, 102),
(23, 103),
(24, 104),
(25, 105),
(26, 106),
(27, 107),
(28, 108),
(29, 109),
(30, 110),
(31, 111),
(32, 112),
(33, 113),
(34, 114),
(35, 115),
(36, 116),
(37, 117),
(38, 118),
(39, 119),
(40, 120),
(1, 121),
(2, 122),
(3, 123),
(4, 124),
(5, 125),
(6, 126),
(7, 127),
(8, 128),
(9, 129),
(10, 130),
(11, 131),
(12, 132),
(13, 133),
(14, 134),
(15, 135),
(16, 136),
(17, 137),
(18, 138),
(19, 139),
(20, 140),
(21, 141),
(22, 142),
(23, 143),
(24, 144),
(25, 145),
(26, 146),
(27, 147),
(28, 148),
(29, 149),
(30, 150),
(31, 1),
(32, 2),
(33, 3),
(34, 4),
(35, 5),
(36, 6),
(37, 7),
(38, 8),
(39, 9),
(40, 10),
(1, 11),
(2, 12),
(3, 13),
(4, 14),
(5, 15),
(6, 16),
(7, 17),
(8, 18),
(9, 19),
(10, 20),
(11, 21),
(12, 22),
(13, 23),
(14, 24),
(15, 25),
(16, 26),
(17, 27),
(18, 28),
(19, 29),
(20, 30),
(21, 31),
(22, 32),
(23, 33),
(24, 34),
(25, 35),
(26, 36),
(27, 37),
(28, 38),
(29, 39),
(30, 40),
(31, 41),
(32, 42),
(33, 43),
(34, 44),
(35, 45),
(36, 46),
(37, 47),
(38, 48),
(39, 49),
(40, 50),
(1, 51),
(2, 52),
(3, 53),
(4, 54),
(5, 55),
(6, 56),
(7, 57),
(8, 58),
(9, 59),
(10, 60),
(11, 61),
(12, 62),
(13, 63),
(14, 64),
(15, 65),
(16, 66),
(17, 67),
(18, 68),
(19, 69),
(20, 70),
(21, 71),
(22, 72),
(23, 73),
(24, 74),
(25, 75),
(26, 76),
(27, 77),
(28, 78),
(29, 79),
(30, 80),
(31, 81),
(32, 82),
(33, 83),
(34, 84),
(35, 85),
(36, 86),
(37, 87),
(38, 88),
(39, 89),
(40, 90),
(1, 91),
(2, 92),
(3, 93),
(4, 94),
(5, 95),
(6, 96),
(7, 97),
(8, 98),
(9, 99),
(10, 100),
(11, 101),
(12, 102),
(13, 103),
(14, 104),
(15, 105),
(16, 106),
(17, 107),
(18, 108),
(19, 109),
(20, 110),
(21, 111),
(22, 112),
(23, 113),
(24, 114),
(25, 115),
(26, 116),
(27, 117),
(28, 118),
(29, 119),
(30, 120),
(31, 121),
(32, 122),
(33, 123),
(34, 124),
(35, 125),
(36, 126),
(37, 127),
(38, 128),
(39, 129),
(40, 130),
(1, 131),
(2, 132),
(3, 133),
(4, 134),
(5, 135),
(6, 136),
(7, 137),
(8, 138),
(9, 139),
(10, 140),
(11, 141),
(12, 142),
(13, 143),
(14, 144),
(15, 145),
(16, 146),
(17, 147),
(18, 148),
(19, 149),
(20, 150);

commit;
