### product list
GET http://localhost:{{$dotenv PORT}}/product/list

### product by id
@productId = 54a4645e-0770-4b90-9cdf-2a66ba0bded5
GET http://localhost:{{$dotenv PORT}}/product/list/{{productId}}

### tags list
GET http://localhost:{{$dotenv PORT}}/product/tags

### product by tag
@productTag = psk
GET http://localhost:{{$dotenv PORT}}/product/tags/{{productTag}}

### product create
POST http://localhost:{{$dotenv PORT}}/product/create
Content-Type: application/json; charset=UTF-8
Authorization: Bearer {{$dotenv ACCESS_TOKEN}}

{
    "name": "psk Wooden Gloves",
    "description": "this is my create Usus aduro vomito consuasor voveo valens. Molestiae enim bos aranea. Deprecator neque excepturi ventus tot claudeo.",
    "price": 18239,
    "tags":[
        {"name":"psk"},
        {"name":"glove"},
        {"name":"wood"}
    ]
}

### product update
PATCH http://localhost:{{$dotenv PORT}}/product/update/{{productId}}
Content-Type: application/json; charset=UTF-8
Authorization: Bearer {{$dotenv ACCESS_TOKEN}}

{
    "name": "psk new Gloves",
    "description": "my glove is perfect!! 100% protect your hand from cold!",
    "price": 99999,
    "tags":[
        {"name":"psk"},
        {"name":"100% warming"},
        {"name":"new"},
        {"name":"my hands!"}
    ]
}

### product delet
DELETE http://localhost:{{$dotenv PORT}}/product/delete/{{productId}}
Authorization: Bearer {{$dotenv ACCESS_TOKEN}}